### PR TITLE
Move Bash tutorial to docs

### PR DESCRIPTION
**Pull request by EmilyGraceSeville7cf**
Please accept this PR only after [this one](https://github.com/onecompiler/cheatsheets/pull/13).

I think it's better to refer to our cheatsheets as syntax references not to duplicate info.

### CODE REVIEW

**Comment by EmilyGraceSeville7cf** [comment]
@onecompiler-ops, is it going to be merged?

**Comment by onecompiler-ops** [comment]
@EmilySeville7cfg  we want to keep the docs as verbose as possible

**Comment by EmilySeville7cfg** [comment]
The problem with verbosity is duplication. On the other hand we can describe the most basic (what?) in all docs.

**Comment by EmilyGraceSeville7cf** [comment]
@onecompiler-ops, [this][tutorial] tutorial is redundant now. You can remove it because everything contained inside it is moved to Bash docs.

[tutorial]: https://github.com/onecompiler/cheatsheets/blob/master/bash.md

**Comment by onecompiler-ops** [comment]
@EmilySeville7cfg  
Usually we try to keep the docs (under the editor) verbose, so that it's easy to copy snippets 
On the other hand CheatSheet is for a quick reference. It's okay to have overlap

**Pull request closed without merging**
